paths:
  backups: C:\Users\Kimball\AppData\Local\Temp\pytest-of-Kimball\pytest-37\test_multiple_backups_ordering0\backups
  database: C:\Users\Kimball\AppData\Local\Temp\pytest-of-Kimball\pytest-37\test_multiple_backups_ordering0\data\test.db
scanning:
  external:
    delay: 1.0
    domains: []
    rate_limit: 30
  internal:
    delay: 0.5
    domains: []
    rate_limit: 60
