alerts:
  expiry_warnings:
  - days: 90
    level: info
  - days: 30
    level: warning
  - days: 7
    level: critical
  failed_scans:
    consecutive_failures: 3
  persistence_file: data/alerts.json
database:
  cache_directory: ~/.ims_cache
  enable_cache: true
  max_pending_writes: 1000
  sync_interval: 30
exports:
  csv:
    delimiter: ','
    encoding: utf-8
  pdf:
    logo: reports/logo.png
    template: reports/template.html
ignore_lists:
  certificates:
    default_patterns:
    - '*.test.com'
    - '*.dev.com'
    - '*.stage.com'
    - '*.qa.com'
    - '*.sandbox.com'
    - '*.cloudflaressl.com'
    - '*.cloudflare.net'
    - '*.akam.net'
    - '*.akamaiedge.net'
    - '*.edgekey.net'
    enabled: true
    hide_from_results: true
    match_by: common_name
    skip_scanning: true
  domains:
    default_patterns:
    - '*.local'
    - '*.test'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test.com'
    - '*.dev.com'
    - '*.stage.com'
    - '*.qa.com'
    - '*.sandbox.com'
    - '*.cloudflaressl.com'
    - '*.cloudflare.net'
    - '*.akam.net'
    - '*.akamaiedge.net'
    - '*.akadns.net'
    - '*.edgekey.net'
    enabled: true
    hide_from_results: true
    pattern_types:
      contains: '*test*'
      exact: example.com
      prefix: '*.example.com'
      suffix: '*.test.com'
    skip_scanning: true
paths:
  backups: /tmp/tmpm0f0txaw/backups
  database: /tmp/tmpm0f0txaw/test.db
proxy_detection:
  ca_fingerprints: null
  ca_serials: []
  ca_subjects: null
  enabled: true
  # Enhanced proxy detection options
  bypass_external: false  # Attempt to bypass proxy for external domains
  bypass_patterns:  # Patterns for domains that should bypass proxy
    - "*.github.com"
    - "*.google.com"
    - "*.microsoft.com"
    - "*.amazon.com"
    - "*.cloudflare.com"
  # Additional proxy detection patterns
  proxy_hostnames:  # Hostnames that indicate proxy certificates
    - "proxy"
    - "firewall"
    - "gateway"
    - "bluecoat"
    - "zscaler"
    - "forcepoint"
  # Validation settings
  enable_hostname_validation: true  # Check for hostname mismatches
  enable_authenticity_validation: true  # Comprehensive authenticity checks
  warn_on_proxy_detection: true  # Generate warnings for detected proxy certificates
scanning:
  certificate:
    rate_limit: 30
  ct:
    rate_limit: 120
  default_rate_limit: 360
  dns:
    rate_limit: 120
    timeout: 5
  external:
    delay: 0
    domains: []
    rate_limit: 120
  internal:
    delay: 0
    domains: []
    rate_limit: 120
  offline_mode: true
  timeouts:
    dns: 2.0
    request: 2
    socket: 2
  whois:
    rate_limit: 120
    timeout: 10
