alerts:
  expiry_warnings:
  - days: 90
    level: info
  - days: 30
    level: warning
  - days: 7
    level: critical
  failed_scans:
    consecutive_failures: 3
  persistence_file: data/alerts.json
exports:
  csv:
    delimiter: ','
    encoding: utf-8
  pdf:
    logo: reports/logo.png
    template: reports/template.html
ignore_lists:
  certificates:
    default_patterns:
    - '*.test.com'
    - '*.dev.com'
    - '*.stage.com'
    - '*.qa.com'
    - '*.sandbox.com'
    - '*.cloudflaressl.com'
    - '*.cloudflare.net'
    - '*.akam.net'
    - '*.akamaiedge.net'
    - '*.edgekey.net'
    enabled: true
    hide_from_results: true
    match_by: common_name
    skip_scanning: true
  domains:
    default_patterns:
    - '*.local'
    - '*.test'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test.com'
    - '*.dev.com'
    - '*.stage.com'
    - '*.qa.com'
    - '*.sandbox.com'
    - '*.cloudflaressl.com'
    - '*.cloudflare.net'
    - '*.akam.net'
    - '*.akamaiedge.net'
    - '*.akadns.net'
    - '*.edgekey.net'
    enabled: true
    hide_from_results: true
    pattern_types:
      contains: '*test*'
      exact: example.com
      prefix: '*.example.com'
      suffix: '*.test.com'
    skip_scanning: true
paths:
  backups: data/backups
  database: data/certificates.db
scanning:
  ct:
    rate_limit: 60
  default_rate_limit: 120
  dns:
    rate_limit: 60
    timeout: 5
  external:
    delay: 0
    domains: []
    rate_limit: 60
  internal:
    delay: 0
    domains: []
    rate_limit: 60
  timeouts:
    dns: 5.0
    request: 15
    socket: 10
  whois:
    rate_limit: 60
    timeout: 10
