
[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
base = "dark"

[server]
runOnSave = true
enableCORS = false
enableXsrfProtection = true

[ui]
hideTopBar = true
